<?php

/**
 * @file
 * Contains commerce_asiapay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_asiapay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_asiapay module.
    case 'help.page.commerce_asiapay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Payment using AsiaPay (PayDollar/PesoPay/SiamPay)') . '</p>';
      return $output;

    default:
  }
}
