commerce_payment.commerce_payment_gateway.plugin.asiapay:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant ID'
    secure_hash_secret:
      type: string
      label: 'Merchant Authentication Hash'
